name: Automatic Updates from Contents
on: [repository_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Will run 'Publish to GitHub Pages with Extensions' workflow"
      - name: Checkout
        uses: actions/checkout@v2
